### ISSUE TITLE
`initialize': wrong number of arguments (given 1, expected 0; required keyword: queue_name) 

### ISSUE THREAD

**Issue by iakovdudinsky** [sldblog/rabbitmq-graph#125]
Returns error when trying to start
rabbit-docker/lib/rabbitmq-graph/route.rb:9:in `initialize': wrong number of arguments (given 1, expected 0; required keyword: queue_name) (ArgumentError)
And this one when trying to run exec with tag integration

$ bundle exec rspec --tag=integration
Run options: include {:integration=>true}
FF
An error occurred in an `after(:context)` hook.
Failure/Error: Process.kill('TERM', @pid)

Errno::EINVAL:
  Invalid argument
# ./spec/app/integration_spec.rb:37:in `kill'
# ./spec/app/integration_spec.rb:37:in `block (2 levels) in <top (required)>'

Failures:

  1) integration maps the claim service route in dot (graphviz) format
     Failure/Error: result = RestClient.get("#{rabbitmq_api_url}/api/consumers/%2f")

     RestClient::NotFound:
       404 Not Found

**Comment by sldblog** [comment]
Hi @EncelBread, thanks for your report. This is on Ruby 3, right?

**Comment by EncelBread** [comment]
> Hi @EncelBread, thanks for your report. This is on Ruby 3, right?

Yes

**Comment by sldblog** [comment]
👍 thanks, I have the integration test expanded to Ruby 3 pending on a branch
will ping here when that's fixed

**Comment by EncelBread** [comment]
> 👍 thanks, I have the integration test expanded to Ruby 3 pending on a branch will ping here when that's fixed

If I will deinstall ruby 3.0 and try 2.7, it may work, right?

**Comment by sldblog** [comment]
Yes, it currently works with 2.7

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1526295/140963244-f91f4675-91c4-4f5c-bd66-f28eaa553c6e.png">

https://github.com/sldblog/rabbitmq-graph/runs/4081182389
